Repository runtipi/runtipi-appstore, pull requests merged in 2024-04, with the labels that each got.

#3035 fix(prowlarr): bump version
  apps/prowlarr/config.json
  apps/prowlarr/docker-compose.yml
Labels: size/XS

#3038 fix(renovate): manage linuxserver versioning correctly.
  renovate.js
Labels: size/XS

#3048 refactor(kasm-workspaces): disable traefik
  apps/kasm-workspaces/config.json
  apps/kasm-workspaces/docker-compose.yml
Labels: size/M

#2936 [APP] Code-server: Add sudo-password
  apps/code-server/config.json
  apps/code-server/docker-compose.yml
  apps/code-server/metadata/description.md
Labels: size/S

#3060 chore: run readme generator with schedule
  .github/workflows/readme-generator.yml
Labels: size/XS

#3049 App/spoolman
  apps/spoolman/config.json
  apps/spoolman/docker-compose.yml
  apps/spoolman/metadata/description.md
  apps/spoolman/metadata/logo.jpg
Labels: size/L

#3115 [FIX] Planning Poker - Force Health Check to use IPV4 instead of IPV6…
  apps/planning-poker/docker-compose.yml
Labels: size/XS

#3141 Add Flightlog
  apps/flightlog/config.json
  apps/flightlog/docker-compose.yml
  apps/flightlog/metadata/description.md
  apps/flightlog/metadata/logo.jpg
Labels: size/M

#3073 add: Cheshire Cat AI app
  apps/cheshire-cat-ai/config.json
  apps/cheshire-cat-ai/docker-compose.yml
  apps/cheshire-cat-ai/metadata/description.md
  apps/cheshire-cat-ai/metadata/logo.jpg
Labels: size/L

#3069 feat(app): add AFFiNE
  apps/affine/config.json
  apps/affine/docker-compose.yml
  apps/affine/metadata/description.md
  apps/affine/metadata/logo.jpg
Labels: size/L

#3228 Refactor/filebrowser
  apps/filebrowser/config.json
  apps/filebrowser/data/config/settings.json
  apps/filebrowser/docker-compose.yml
Labels: size/S

#3122 add: Stalwart Mail app
  apps/stalwart-mail/config.json
  apps/stalwart-mail/docker-compose.yml
  apps/stalwart-mail/metadata/description.md
  apps/stalwart-mail/metadata/logo.jpg
Labels: size/L

#3258 Add: Komga app
  apps/komga/config.json
  apps/komga/docker-compose.yml
  apps/komga/metadata/description.md
  apps/komga/metadata/logo.jpg
Labels: size/M

#3310 chore: update komga image
  apps/komga/metadata/logo.jpg
Labels: size/XS
