Repository runtipi/runtipi-appstore, pull requests merged in 2024-07, with the labels that each got.

#3972 refactor(umami): use unless stopped restart policy
  apps/umami/config.json
  apps/umami/docker-compose.yml
Labels: size/XS

#3990 fix(whisparr): bump version
  apps/whisparr/config.json
  apps/whisparr/docker-compose.yml
Labels: size/XS

#4000 feat: olivetin app
  apps/olivetin/config.json
  apps/olivetin/data/config.yaml
  apps/olivetin/docker-compose.yml
  apps/olivetin/metadata/description.md
  apps/olivetin/metadata/logo.jpg
Labels: size/L

#4005 refactor(olivetin): fix wrong port
  apps/olivetin/config.json
  apps/olivetin/docker-compose.yml
Labels: size/XS

#4006 feat(code-server): add mounts to edit user config and app data
  apps/code-server/config.json
  apps/code-server/docker-compose.yml
Labels: size/XS

#4017 refactor(olivetin): use latest image
  apps/olivetin/config.json
  apps/olivetin/docker-compose.yml
Labels: size/XS

#3691 [APP] GrampsWeb
  apps/grampsweb/config.json
  apps/grampsweb/docker-compose.yml
  apps/grampsweb/metadata/description.md
  apps/grampsweb/metadata/logo.jpg
Labels: size/L

#4043 refactor(mongo-express): use text type in mongo ip to allow internal …
  apps/mongo-express/config.json
  apps/mongo-express/metadata/description.md
  apps/mongo/config.json
  apps/mongo/metadata/description.md
Labels: size/M

#4022 [APP] pinchflat - changed image tag to v2024.6.25
  apps/pinchflat/config.json
  apps/pinchflat/docker-compose.yml
Labels: size/XS

#4051 fix(semaphore): fix traefik port
  apps/semaphore/config.json
  apps/semaphore/docker-compose.yml
Labels: size/XS

#4054 fix(semaphore): fix labels
  apps/semaphore/config.json
  apps/semaphore/docker-compose.yml
Labels: size/M

#4108 feat: cup app
  apps/cup/config.json
  apps/cup/docker-compose.yml
  apps/cup/metadata/description.md
  apps/cup/metadata/logo.jpg
Labels: size/M

#4109 fix(cup): use command instead of entrypoint
  apps/cup/config.json
  apps/cup/docker-compose.yml
Labels: size/XS

#4135 refactor(semaphore): allow local repositories
  apps/semaphore/config.json
  apps/semaphore/docker-compose.yml
  apps/semaphore/metadata/description.md
Labels: size/XS

#4137 refactor(semaphore): store db data in db folder
  apps/semaphore/config.json
  apps/semaphore/docker-compose.yml
Labels: size/XS

#4157 Fix wordpress subdomain
  apps/wordpress/docker-compose.yml
Labels: size/M

#4089 Make a fix to change traefik labels, it currently does not work prope…
  apps/changedetection/docker-compose.yml
Labels: size/M

#4168 Added app Docmost
  apps/docmost/config.json
  apps/docmost/docker-compose.yml
  apps/docmost/metadata/description.md
  apps/docmost/metadata/logo.jpg
Labels: size/L

#4171 feat: e2e tests for apps
  .github/scripts/renovate-app-version.sh
  .github/scripts/start-tipi.sh
  .github/workflows/app-e2e.yml
  .github/workflows/renovate-ci.yml
  .gitignore
  e2e/fixtures/fixtures.ts
  e2e/helpers/helpers.ts
  e2e/install.spec.ts
  package.json
  playwright.config.ts
  pnpm-lock.yaml
Labels: size/L

#4230 refactor(open-webui): use semver for version instead of git commits
  apps/open-webui/config.json
  apps/open-webui/docker-compose.json
  apps/open-webui/docker-compose.yml
Labels: size/S

#4228 chore(memos): change logo
  apps/memos/config.json
  apps/memos/metadata/logo.jpg
Labels: size/XS

#4241 Update docker-compose.yml to include HOST_UID and HOST_GID for Tube Archivist
  apps/tubearchivist/config.json
  apps/tubearchivist/docker-compose.yml
Labels: size/XS

#4269 Revert "chore(deps): update semaphoreui/semaphore docker tag to v2.19.10"
  apps/semaphore/config.json
  apps/semaphore/docker-compose.yml
Labels: size/XS

#4302 fix(semaphore): fix version
  apps/semaphore/config.json
  apps/semaphore/docker-compose.yml
Labels: size/XS

#4307 fix(semaphore): fix version
  apps/semaphore/config.json
  apps/semaphore/docker-compose.yml
Labels: size/XS
