Repository runtipi/runtipi-appstore, pull requests merged in 2024-03, with the labels that each got.

#2651 Add Outline
  apps/outline/config.json
  apps/outline/data/nginx/default.conf
  apps/outline/data/oidc-config.json.template
  apps/outline/docker-compose.yml
  apps/outline/metadata/description.md
  apps/outline/metadata/logo.jpg
Labels: size/L

#2547 App/wallos
  apps/wallos/config.json
  apps/wallos/docker-compose.yml
  apps/wallos/metadata/description.md
  apps/wallos/metadata/logo.jpg
Labels: size/M

#2710 feat: add windows app
  apps/windows/config.json
  apps/windows/docker-compose.yml
  apps/windows/metadata/description.md
  apps/windows/metadata/logo.jpg
Labels: size/L

#2713 fix(windows): use correct storage location
  apps/windows/docker-compose.yml
Labels: size/XS

#2746 feat(windows): use multiple choise instead of text
  apps/windows/config.json
Labels: size/S

#2750 chore: update windows app logo
  apps/windows/config.json
  apps/windows/metadata/logo.jpg
Labels: size/XS

#2753 app(radarr): bump to 5.3.6
  apps/radarr/config.json
  apps/radarr/docker-compose.yml
Labels: size/XS

#2755 app(overseerr): switch to linuxserver image and ghcr
  apps/overseerr/config.json
  apps/overseerr/docker-compose.yml
Labels: size/S

#2757 fix(overseerr): version
  apps/overseerr/config.json
  apps/overseerr/docker-compose.yml
Labels: size/XS

#2858 [APP] Atuin: switch to explicit tag
  apps/atuin/config.json
  apps/atuin/docker-compose.yml
Labels: size/S

#2724 [APP] Ghost - Add mail configuration
  apps/ghost/config.json
  apps/ghost/docker-compose.yml
Labels: size/M

#2793 [APP] Add Bitcoin core
  apps/bitcoind/config.json
  apps/bitcoind/docker-compose.yml
  apps/bitcoind/metadata/description.md
  apps/bitcoind/metadata/logo.jpg
Labels: size/M

#2886 Update immich image link
  apps/immich/metadata/description.md
Labels: size/XS

#2897 Update immich logo
  apps/immich/metadata/logo.jpg
Labels: size/XS

#2887 wg-easy: update container registry & version
  apps/wg-easy/config.json
  apps/wg-easy/docker-compose.yml
Labels: size/XS

#2914 feat: add getashell app
  apps/getashell/config.json
  apps/getashell/docker-compose.yml
  apps/getashell/metadata/description.md
  apps/getashell/metadata/logo.jpg
Labels: size/M

#2972 refactor(getashell): include extra compose config
  apps/getashell/config.json
  apps/getashell/docker-compose.yml
Labels: size/XS

#2978 refactor(getashell): update
  apps/getashell/config.json
  apps/getashell/docker-compose.yml
Labels: size/XS

#2981 refactor(getashell): update
  apps/getashell/config.json
  apps/getashell/docker-compose.yml
Labels: size/XS

#2984 refactor(getashell): update
  apps/getashell/config.json
  apps/getashell/docker-compose.yml
  apps/getashell/metadata/description.md
Labels: size/XS

#2985 Update config.json
  apps/getashell/config.json
Labels: size/XS
