Repository runtipi/runtipi-appstore, pull requests merged in 2024-12, with the labels that each got.

#5824 feat: smallweb app
  apps/smallweb/config.json
  apps/smallweb/data/www/index.md
  apps/smallweb/docker-compose.yml
  apps/smallweb/metadata/description.md
  apps/smallweb/metadata/logo.jpg
Labels: size/L

#5827 Fix/smallweb
  apps/smallweb/config.json
  apps/smallweb/docker-compose.yml
Labels: size/XS

#5840 refactor(smallweb): require app to be exposed
  apps/smallweb/config.json
Labels: size/XS

#5841 refactor(smallweb): prompt user for a domain
  apps/smallweb/config.json
  apps/smallweb/docker-compose.yml
  apps/smallweb/metadata/description.md
Labels: size/S

#5866 Add dynamic compose for it-tools
  apps/it-tools/config.json
  apps/it-tools/docker-compose.json
Labels: size/S

#5883 Add dynamic compose for baikal
  apps/baikal/config.json
  apps/baikal/docker-compose.json
Labels: size/S

#5885 Add dynamic compose for chatpad
  apps/chatpad/config.json
  apps/chatpad/docker-compose.json
Labels: size/S

#5886 Add dynamic compose for databag
  apps/databag/config.json
  apps/databag/docker-compose.json
Labels: size/S

#5887 Add dynamic compose for esphome
  apps/esphome/config.json
  apps/esphome/docker-compose.json
Labels: size/M

#5888 Add dynamic compose for homarr
  apps/homarr/config.json
  apps/homarr/docker-compose.json
Labels: size/M

#5890 Add dynamic compose for jellyfin-vue
  apps/jellyfin-vue/config.json
  apps/jellyfin-vue/docker-compose.json
Labels: size/S

#5891 Add dynamic compose for jellyfin
  apps/jellyfin/config.json
  apps/jellyfin/docker-compose.json
Labels: size/M

#5892 Add dynamic compose for jellyseerr
  apps/jellyseerr/config.json
  apps/jellyseerr/docker-compose.json
Labels: size/S

#5893 Add dynamic compose for lidarr-deemix
  apps/lidarr-deemix/config.json
  apps/lidarr-deemix/docker-compose.json
Labels: size/M

#5894 Add dynamic compose for lidarr
  apps/lidarr/config.json
  apps/lidarr/docker-compose.json
Labels: size/M

#5895 Add dynamic compose for lobe-chat
  apps/lobe-chat/config.json
  apps/lobe-chat/docker-compose.json
Labels: size/S

#5897 Add dynamic compose for memos
  apps/memos/config.json
  apps/memos/docker-compose.json
Labels: size/S

#5899 Add dynamic compose for mongo-express
  apps/mongo-express/config.json
  apps/mongo-express/docker-compose.json
Labels: size/S

#5900 Add dynamic compose for mongo
  apps/mongo/config.json
  apps/mongo/docker-compose.json
Labels: size/S

#5901 Dynamic compose/mstream
  apps/mstream/config.json
  apps/mstream/docker-compose.json
  apps/mstream/docker-compose.yml
Labels: size/M

#5902 Add dynamic compose for obsidian-livesync
  apps/obsidian-livesync/config.json
  apps/obsidian-livesync/docker-compose.json
Labels: size/S

#5903 Add dynamic compose for olivetin
  apps/olivetin/config.json
  apps/olivetin/docker-compose.json
Labels: size/S

#5905 Add dynamic compose for ollama-cpu
  apps/ollama-cpu/config.json
  apps/ollama-cpu/docker-compose.json
Labels: size/S

#5921 Dynamic compose/podfetch
  apps/podfetch/config.json
  apps/podfetch/docker-compose.json
Labels: size/M

#5916 Add dynamic compose for paperless-ngx
  apps/paperless-ngx/config.json
  apps/paperless-ngx/docker-compose.json
Labels: size/M

#5927 fix(duplicati): add missing env variable
  apps/duplicati/config.json
  apps/duplicati/docker-compose.yml
Labels: size/S

#5933 Add dynamic compose for serge
  apps/serge/config.json
  apps/serge/docker-compose.json
Labels: size/S

#5936 fix(wg-easy): remove char limit on hash
  apps/wg-easy/config.json
  apps/wg-easy/docker-compose.yml
Labels: size/S

#5937 Add dynamic compose for spacedrive
  apps/spacedrive/config.json
  apps/spacedrive/docker-compose.json
Labels: size/S

#5940 Add dynamic compose for tautulli
  apps/tautulli/config.json
  apps/tautulli/docker-compose.json
Labels: size/S

#5938 Add dynamic compose for spoolman
  apps/spoolman/config.json
  apps/spoolman/docker-compose.json
Labels: size/S

#5941 Dynamic compose/teddit
  apps/teddit/config.json
  apps/teddit/docker-compose.json
Labels: size/M

#5942 Add dynamic compose for trilium
  apps/trilium/config.json
  apps/trilium/docker-compose.json
Labels: size/S

#5943 Add dynamic compose for wizarr
  apps/wizarr/config.json
  apps/wizarr/docker-compose.json
Labels: size/S

#5965 Add dynamic compose for grafana
  apps/grafana/config.json
  apps/grafana/docker-compose.json
Labels: size/S

#5966 Add dynamic compose for mdns-repeater
  apps/mdns-repeater/config.json
  apps/mdns-repeater/docker-compose.json
Labels: size/S

#5967 Add dynamic compose for pinchflat
  apps/pinchflat/config.json
  apps/pinchflat/docker-compose.json
Labels: size/M

#5968 Add dynamic compose for wallos
  apps/wallos/config.json
  apps/wallos/docker-compose.json
Labels: size/M

#5969 Add dynamic compose for whoogle
  apps/whoogle/config.json
  apps/whoogle/docker-compose.json
Labels: size/S

#5984 Add dynamic compose for hammond (+ timezone adjustment)
  apps/hammond/config.json
  apps/hammond/docker-compose.json
  apps/hammond/docker-compose.yml
Labels: size/M

#5985 Add dynamic compose for kanboard
  apps/kanboard/config.json
  apps/kanboard/docker-compose.json
Labels: size/S

#5986 Add dynamic compose for koillection
  apps/koillection/config.json
  apps/koillection/docker-compose.json
Labels: size/M

#5988 Add dynamic compose for linkwarden
  apps/linkwarden/config.json
  apps/linkwarden/docker-compose.json
Labels: size/M

#5989 Add dynamic compose for tandoor
  apps/tandoor/config.json
  apps/tandoor/docker-compose.json
Labels: size/M

#5990 Add dynamic compose for tasks-md
  apps/tasks-md/config.json
  apps/tasks-md/docker-compose.json
Labels: size/M

#5991 Add dynamic compose for vaultwarden
  apps/vaultwarden/config.json
  apps/vaultwarden/docker-compose.json
Labels: size/S

#6047 Add dynamic compose for emby
  apps/emby/config.json
  apps/emby/docker-compose.json
Labels: size/M

#6048 Add dynamic compose for fireshare
  apps/fireshare/config.json
  apps/fireshare/docker-compose.json
Labels: size/M

#6051 Add dynamic compose for flatnotes
  apps/flatnotes/config.json
  apps/flatnotes/docker-compose.json
Labels: size/S

#6052 Add dynamic compose for flightlog
  apps/flightlog/config.json
  apps/flightlog/docker-compose.json
Labels: size/S

#6053 Add dynamic compose for gotify
  apps/gotify/config.json
  apps/gotify/docker-compose.json
Labels: size/S

#6054 Add dynamic compose for grav
  apps/grav/config.json
  apps/grav/docker-compose.json
Labels: size/S

#6055 Dynamic compose/kapowarr
  apps/kapowarr/config.json
  apps/kapowarr/docker-compose.json
  apps/kapowarr/docker-compose.yml
Labels: size/M

#6056 Add dynamic compose for zipline
  apps/zipline/config.json
  apps/zipline/docker-compose.json
Labels: size/M

#6106 Add dynamic compose for mixpost
  apps/mixpost/config.json
  apps/mixpost/docker-compose.json
Labels: size/M

#6107 Dynamic compose/mixpost pro
  apps/mixpost-pro/config.json
  apps/mixpost-pro/docker-compose.json
Labels: size/M

#6091 Add dynamic compose for code-server
  apps/code-server/config.json
  apps/code-server/docker-compose.json
Labels: size/M

#6092 Add dynamic compose for grocy
  apps/grocy/config.json
  apps/grocy/docker-compose.json
Labels: size/S

#6097 Add dynamic compose for komga
  apps/komga/config.json
  apps/komga/docker-compose.json
Labels: size/S

#6095 Add dynamic compose for halo
  apps/halo/config.json
  apps/halo/docker-compose.json
Labels: size/M

#6096 Add dynamic compose for kavita
  apps/kavita/config.json
  apps/kavita/docker-compose.json
Labels: size/M

#6098 Add dynamic compose for nodered
  apps/nodered/config.json
  apps/nodered/docker-compose.json
Labels: size/S

#6099 Add dynamic compose for pingvin-share
  apps/pingvin-share/config.json
  apps/pingvin-share/docker-compose.json
Labels: size/S

#6100 Add dynamic compose for planning-poker
  apps/planning-poker/config.json
  apps/planning-poker/docker-compose.json
Labels: size/S

#6101 Add dynamic compose for ryot
  apps/ryot/config.json
  apps/ryot/docker-compose.json
Labels: size/M

#6102 Add dynamic compose for searxng
  apps/searxng/config.json
  apps/searxng/docker-compose.json
Labels: size/S

#6103 Add dynamic compose for silverbullet
  apps/silverbullet/config.json
  apps/silverbullet/docker-compose.json
Labels: size/S

#6104 Add dynamic compose for vikunja
  apps/vikunja/config.json
  apps/vikunja/docker-compose.json
Labels: size/M

#6105 Add dynamic compose for wekan
  apps/wekan/config.json
  apps/wekan/docker-compose.json
Labels: size/M

#6112 Add dynamic compose for getashell
  apps/getashell/config.json
  apps/getashell/docker-compose.json
Labels: size/M

#6113 Dynamic compose/haven
  apps/haven/config.json
  apps/haven/docker-compose.json
Labels: size/M

#5404 Add dynamic compose for dokuwiki
  apps/dokuwiki/config.json
  apps/dokuwiki/docker-compose.json
  apps/dokuwiki/docker-compose.yml
Labels: size/M

#6133 chore: update docmost logo
  apps/docmost/metadata/logo.jpg
Labels: size/XS

#6135 chore: bump docmost version
  apps/docmost/config.json
Labels: size/XS

#6141 Add dynamic compose for chatgpt UI
  apps/chatgpt-ui/config.json
  apps/chatgpt-ui/docker-compose.json
Labels: size/M

#6156 Add dynamic compose for calcom
  apps/calcom/config.json
  apps/calcom/docker-compose.json
Labels: size/M

#6157 Add dynamic compose for calibre-web
  apps/calibre-web/config.json
  apps/calibre-web/docker-compose.json
Labels: size/M

#6158 Add dynamic compose for ctfd
  apps/ctfd/config.json
  apps/ctfd/docker-compose.json
Labels: size/M

#6159 Add dynamic compose for hoarder
  apps/hoarder/config.json
  apps/hoarder/docker-compose.json
Labels: size/M

#6160 Add dynamic compose for librephotos
  apps/librephotos/config.json
  apps/librephotos/docker-compose.json
Labels: size/L

#6161 Add dynamic compose for n8n (v0)
  apps/n8n/config.json
  apps/n8n/docker-compose.json
Labels: size/S

#6162 Add dynamic compose for owncast
  apps/owncast/config.json
  apps/owncast/docker-compose.json
Labels: size/S

#6163 Add dynamic compose for shlink
  apps/shlink/config.json
  apps/shlink/docker-compose.json
Labels: size/M

#6164 Dynamic compose/viewtube
  apps/viewtube/config.json
  apps/viewtube/docker-compose.json
Labels: size/M

#6167 [Calibre-Web] Add calibre volume for database
  apps/calibre-web/config.json
  apps/calibre-web/data/calibre/metadata.db
  apps/calibre-web/docker-compose.json
  apps/calibre-web/docker-compose.yml
  apps/calibre-web/metadata/description.md
Labels: size/S
