Repository runtipi/runtipi-appstore, pull requests merged in 2024-10, with the labels that each got.

#5042 Update Firefly III and data importer
  apps/firefly-iii-data-importer/config.json
  apps/firefly-iii-data-importer/docker-compose.yml
  apps/firefly-iii/config.json
  apps/firefly-iii/docker-compose.yml
Labels: size/S

#5085 Feat/watchyourlan
  apps/__tests__/apps.test.ts
  apps/watchyourlan/config.json
  apps/watchyourlan/docker-compose.json
  apps/watchyourlan/docker-compose.yml
  apps/watchyourlan/metadata/description.md
  apps/watchyourlan/metadata/logo.jpg
Labels: size/M

#5084 Update qbittorrent 5.0.0
  apps/qbittorrent/config.json
  apps/qbittorrent/docker-compose.yml
Labels: size/XS

#5124 refactor(archivebox): remove unnecessary volume
  apps/archivebox/config.json
  apps/archivebox/docker-compose.yml
Labels: size/XS

#5122 Adding LibreSpeed
  apps/librespeed/config.json
  apps/librespeed/docker-compose.yml
  apps/librespeed/metadata/description.md
  apps/librespeed/metadata/logo.jpg
Labels: size/M

#5153 LibreSpeed - Add a config volume for index.html configuration.
  apps/librespeed/config.json
  apps/librespeed/docker-compose.yml
Labels: size/XS

#4915 chore: migrate cup to dynamic compose
  apps/cup/config.json
  apps/cup/docker-compose.json
Labels: size/S

#5155 refactor(atuin): clean up
  apps/atuin/config.json
  apps/atuin/docker-compose.yml
Labels: size/M

#4923 chore: migrate homepage to dynamic compose
  apps/homepage/config.json
  apps/homepage/docker-compose.json
Labels: size/S

#4914 chore: migrate anse to dynamic compose
  apps/anse/config.json
  apps/anse/docker-compose.json
Labels: size/S

#5156 chore: bump cup version
  apps/cup/config.json
Labels: size/XS

#4916 chore: migrate ghost to dynamic compose
  apps/ghost/config.json
  apps/ghost/docker-compose.json
Labels: size/M

#5070 Make Dashy exposable
  apps/dashy/config.json
Labels: size/XS

#4922 chore: migrate adguard to dynamic compose
  apps/adguard/config.json
  apps/adguard/docker-compose.json
Labels: size/M

#5157 fix(atuin): add atuin port env variable
  apps/atuin/config.json
  apps/atuin/docker-compose.yml
Labels: size/XS

#5158 chore(adguard): bump version
  apps/adguard/config.json
  apps/adguard/docker-compose.json
Labels: size/XS

#5171 app: homer
  apps/homer/config.json
  apps/homer/docker-compose.json
  apps/homer/docker-compose.yml
  apps/homer/metadata/description.md
  apps/homer/metadata/logo.jpg
Labels: size/L

#5174 fix(homer): add data directory
  apps/homer/config.json
  apps/homer/data/.gitkeep
Labels: size/XS

#5192 fix(emqx): fix logo
  apps/emqx/config.json
  apps/emqx/metadata/logo.jpg
Labels: size/XS

#5227 Fix immich port 3001 -> 2283
  apps/immich/config.json
  apps/immich/docker-compose.yml
Labels: size/XS

#5262 Dynamic compose for Monica
  apps/monica/config.json
  apps/monica/docker-compose.json
Labels: size/M

#4603 [App] Metabase
  apps/metabase/config.json
  apps/metabase/docker-compose.json
  apps/metabase/docker-compose.yml
  apps/metabase/metadata/description.md
  apps/metabase/metadata/logo.jpg
Labels: size/L

#5325 Add dynamic compose for changedetection
  apps/changedetection/config.json
  apps/changedetection/docker-compose.json
Labels: size/M

#5326 Add dynamic compose for deemix
  apps/deemix/config.json
  apps/deemix/docker-compose.json
Labels: size/M

#5362 Fix Affine DB healthcheck
  apps/affine/docker-compose.yml
Labels: size/XS

#5328 Add dynamic compose for metube
  apps/metube/config.json
  apps/metube/docker-compose.json
Labels: size/M

#5331 Add dynamic compose for beszel
  apps/beszel/config.json
  apps/beszel/docker-compose.json
Labels: size/M

#5327 Add dynamic compose for filebrowser
  apps/filebrowser/config.json
  apps/filebrowser/docker-compose.json
Labels: size/M

#5364 Add dynamic compose for ntfy
  apps/ntfy/config.json
  apps/ntfy/docker-compose.json
Labels: size/M

#5329 Add dynamic compose for navidrome
  apps/navidrome/config.json
  apps/navidrome/docker-compose.json
Labels: size/M

#5336 Add dynamic compose for archivebox
  apps/archivebox/config.json
  apps/archivebox/docker-compose.json
Labels: size/L

#5332 Add dynamic compose for beszel-agent
  apps/beszel-agent/config.json
  apps/beszel-agent/docker-compose.json
Labels: size/M

#5374 chore: migrate prettier & eslint to biome
  .eslintrc.js
  .github/workflows/ci.yml
  .husky/_/pre-commit
  .husky/_/prepare-commit-msg
  .husky/pre-commit
  .prettierrc.js
  biome.json
  lefthook.yml
  package.json
Labels: size/L

#5369 Add dynamic compose for freshrss
  apps/freshrss/config.json
  apps/freshrss/docker-compose.json
Labels: size/M

#5368 Add dynamic compose for mind
  apps/mind/config.json
  apps/mind/docker-compose.json
Labels: size/M

#5365 Add dynamic compose for nginx
  apps/nginx/config.json
  apps/nginx/docker-compose.json
Labels: size/M

#5359 Add dynamic compose for cyberchef
  apps/cyberchef/config.json
  apps/cyberchef/docker-compose.json
Labels: size/M

#5337 Add dynamic compose for audiobookshelf
  apps/audiobookshelf/config.json
  apps/audiobookshelf/docker-compose.json
Labels: size/M

#5357 Add dynamic compose for nextgba
  apps/nextgba/config.json
  apps/nextgba/docker-compose.json
Labels: size/M

#5356 Add dynamic compose for hello-world
  apps/hello-world/config.json
  apps/hello-world/docker-compose.json
Labels: size/M

#5338 Add dynamic compose for moodist
  apps/moodist/config.json
  apps/moodist/docker-compose.json
Labels: size/M

#5355 Add dynamic compose for dockge
  apps/dockge/config.json
  apps/dockge/docker-compose.json
Labels: size/M

#5358 Add dynamic compose for pairdrop
  apps/pairdrop/config.json
  apps/pairdrop/docker-compose.json
Labels: size/M

#5352 Add dynamic compose for dailytxt
  apps/dailytxt/config.json
  apps/dailytxt/docker-compose.json
Labels: size/M

#5340 Add dynamic compose for excalidraw
  apps/excalidraw/config.json
  apps/excalidraw/docker-compose.json
Labels: size/M

#5388 feat: adguard home sync app
  .prettierignore
  apps/adguardhome-sync/config.json
  apps/adguardhome-sync/data/adguardhome-sync.yaml.template
  apps/adguardhome-sync/docker-compose.json
  apps/adguardhome-sync/docker-compose.yml
  apps/adguardhome-sync/metadata/description.md
  apps/adguardhome-sync/metadata/logo.jpg
Labels: size/L

#5391 Refactor/syncthing
  apps/syncthing/config.json
  apps/syncthing/docker-compose.yml
Labels: size/S

#5392 fix: syncthing default hostname
  apps/syncthing/config.json
  apps/syncthing/docker-compose.yml
Labels: size/XS

#5382 Add dynamic compose for dashy
  apps/dashy/config.json
  apps/dashy/docker-compose.json
Labels: size/S

#5381 Add dynamic compose for budibase
  apps/budibase/config.json
  apps/budibase/docker-compose.json
Labels: size/S
