Repository runtipi/runtipi-appstore, pull requests merged in 2024-01, with the labels that each got.

#2204 Update: qbittorrent description
  apps/qbittorrent/metadata/description.md
Labels: size/XS

#2235 fix(github): use arrow for upvote
  .github/DISCUSSION_TEMPLATE/requests.yml
Labels: size/XS

#2254 fix(2fauth): blank page, added env. vars
  apps/2fauth/config.json
  apps/2fauth/docker-compose.yml
Labels: size/XS

#2256 fix(trilium): back to stable version (close #2169)
  apps/trilium/config.json
  apps/trilium/docker-compose.yml
Labels: size/XS

#2257 fix(lodestone): adjust data permissions
  apps/lodestone-core/config.json
Labels: size/XS

#2177 chore: add auto readme generator
  .github/workflows/app-list-generator.yml
  app-list-generator.ts
Labels: size/L

#2258 [create-pull-request] automated change
  README.md
Labels: size/L

#2259 fix(scrypted): bump version
  apps/scrypted/config.json
  apps/scrypted/docker-compose.yml
Labels: size/XS

#2261 refactor(readme-generator): use better names
  .github/workflows/app-list-generator.yml
  .github/workflows/readme-generator.yml
  readme-generator.ts
Labels: size/M

#2262 fix(workflows): fix typo
  .github/workflows/readme-generator.yml
Labels: size/XS

#2263 fix(workflows): fix typo
  .github/workflows/readme-generator.yml
Labels: size/XS

#2271 feat(readme-generator): move the readme file outside of the script an…
  .github/scripts/readme-generator.ts
  README.md
  readme-generator.ts
  templates/README.md
Labels: size/L

#2274 fix(workflows): use correct path in the readme generator
  .github/workflows/readme-generator.yml
Labels: size/XS

#2290 [App] Flowise AI
  apps/flowise/config.json
  apps/flowise/docker-compose.yml
  apps/flowise/metadata/description.md
  apps/flowise/metadata/logo.jpg
Labels: size/L

#2323 [changedetection] Update browserless comment
  apps/changedetection/docker-compose.yml
Labels: size/L

#2316 Add Maintainerr
  apps/maintainerr/config.json
  apps/maintainerr/docker-compose.yml
  apps/maintainerr/metadata/description.md
  apps/maintainerr/metadata/logo.jpg
Labels: size/M

#2060 [APP] Atuin
  .gitignore
  apps/atuin/config.json
  apps/atuin/docker-compose.yml
  apps/atuin/metadata/description.md
  apps/atuin/metadata/logo.jpg
Labels: size/L

#2291 [APP] Silverbullet
  apps/silverbullet/config.json
  apps/silverbullet/docker-compose.yml
  apps/silverbullet/metadata/description.md
  apps/silverbullet/metadata/logo.jpg
Labels: size/M
