Repository runtipi/runtipi-appstore, pull requests merged in 2024-09, with the labels that each got.

#4782 Add hoarder
  apps/hoarder/config.json
  apps/hoarder/docker-compose.yml
  apps/hoarder/metadata/description.md
  apps/hoarder/metadata/logo.jpg
Labels: size/L

#4822 Revert "chore(deps): update lscr.io/linuxserver/qbittorrent docker tag to v20"
  apps/qbittorrent/config.json
  apps/qbittorrent/docker-compose.yml
Labels: automerge, size/XS

#4824 Ab ohiccups/master
  apps/emby/config.json
  apps/emby/docker-compose.yml
  apps/emby/metadata/description.md
  apps/emby/metadata/logo.jpg
Labels: size/M

#4840 refactor(activepieces): convert config to json format
  apps/activepieces/config.json
  apps/activepieces/docker-compose.json
Labels: size/M

#3434 add(app): mempool
  apps/mempool/config.json
  apps/mempool/docker-compose.yml
  apps/mempool/metadata/description.md
  apps/mempool/metadata/logo.jpg
Labels: size/L

#4921 Update compose schema to support custom interface for ports
  apps/compose-schema.json
Labels: size/XS

#4920 [App] Mempool: Update created & updated fields
  apps/mempool/config.json
Labels: size/XS

#4942 add(app): emqx
  apps/emqx/config.json
  apps/emqx/docker-compose.yml
  apps/emqx/metadata/description.md
  apps/emqx/metadata/logo.jpg
Labels: size/L

#5003 refactor(vaultwarden): allow the use of argon2
  apps/vaultwarden/config.json
Labels: size/XS

#5020 fix/affine
  apps/affine/config.json
  apps/affine/docker-compose.yml
Labels: size/S

#5021 fix/linkwarden
  apps/linkwarden/config.json
  apps/linkwarden/docker-compose.yml
Labels: size/S

#5017 fix/nocodb
  apps/nocodb/config.json
  apps/nocodb/docker-compose.yml
Labels: size/S
