Repository runtipi/runtipi-appstore, pull requests merged in 2024-02, with the labels that each got.

#2312 [App] Anse
  apps/anse/config.json
  apps/anse/docker-compose.yml
  apps/anse/metadata/description.md
  apps/anse/metadata/logo.jpg
Labels: size/M

#2304 Make filestash persist data
  apps/filestash/config.json
  apps/filestash/docker-compose.yml
Labels: size/XS

#2170 [Immich] Update image tag to use official registry
  apps/immich/docker-compose.yml
Labels: size/XS

#2393 [App] ArchiveBox
  apps/archivebox/config.json
  apps/archivebox/docker-compose.yml
  apps/archivebox/metadata/description.md
  apps/archivebox/metadata/logo.jpg
Labels: size/L

#2392 [App] add DB_QUERY_LIMIT_DEFAULT env to NocoDB
  apps/nocodb/config.json
  apps/nocodb/docker-compose.yml
Labels: size/XS

#2337 App/calcom
  apps/calcom/config.json
  apps/calcom/docker-compose.yml
  apps/calcom/metadata/description.md
  apps/calcom/metadata/logo.jpg
Labels: size/XL

#2402 APP Maintainerr update
  apps/maintainerr/config.json
  apps/maintainerr/docker-compose.yml
Labels: size/S

#2391 [App] upgrade n8n + add pgsql
  apps/n8n/config.json
  apps/n8n/data/init-data.sh
  apps/n8n/docker-compose.yml
  apps/n8n/metadata/description.md
Labels: size/M

#2481 Add Heimdall
  apps/heimdall/config.json
  apps/heimdall/docker-compose.yml
  apps/heimdall/metadata/description.md
  apps/heimdall/metadata/logo.jpg
Labels: size/M

#2494 app(prowlarr): bump version
  apps/prowlarr/config.json
  apps/prowlarr/docker-compose.yml
Labels: size/XS

#2532 feat: add next gba app
  apps/nextgba/config.json
  apps/nextgba/docker-compose.yml
  apps/nextgba/metadata/description.md
  apps/nextgba/metadata/logo.jpg
Labels: size/M

#2540 Bug fixes for Calcom
  apps/calcom/config.json
  apps/calcom/docker-compose.yml
Labels: size/S

#2558 Update description.md
  apps/gandi-livedns/metadata/description.md
Labels: size/S

#2561 Update config.json
  apps/gandi-livedns/config.json
Labels: size/S

#2559 Update docker-compose.yml
  apps/gandi-livedns/docker-compose.yml
Labels: size/XS

#2531 App/moodist
  apps/moodist/config.json
  apps/moodist/docker-compose.yml
  apps/moodist/metadata/description.md
  apps/moodist/metadata/logo.jpg
Labels: size/M

#2549 App/zigbee2mqtt and App/eclipse-mosquitto
  apps/eclipse-mosquitto/config.json
  apps/eclipse-mosquitto/data/config/mosquitto.conf
  apps/eclipse-mosquitto/data/data/.gitkeep
  apps/eclipse-mosquitto/data/scripts/dynsec-setup.sh
  apps/eclipse-mosquitto/docker-compose.yml
  apps/eclipse-mosquitto/metadata/caledo_mgm_center.png
  apps/eclipse-mosquitto/metadata/description.md
  apps/eclipse-mosquitto/metadata/logo.jpg
  apps/zigbee2mqtt/config.json
  apps/zigbee2mqtt/data/.gitkeep
  apps/zigbee2mqtt/docker-compose.yml
  apps/zigbee2mqtt/metadata/description.md
  apps/zigbee2mqtt/metadata/logo.jpg
Labels: size/L

#2586 chore: fix description and logo in nextgba
  apps/nextgba/config.json
  apps/nextgba/metadata/description.md
  apps/nextgba/metadata/logo.jpg
Labels: size/S

#2575 Update Jellyfin to 10.8.13 - docker-compose.yml
  apps/jellyfin/docker-compose.yml
Labels: size/XS

#2612 Update zigbee2mqtt description
  apps/zigbee2mqtt/metadata/description.md
Labels: size/XS

#2603 fix: atuin database not initialiazing on fresh install
  apps/atuin/docker-compose.yml
Labels: size/XS
