Repository runtipi/runtipi-appstore, pull requests merged in 2024-11, with the labels that each got.

#5389 App/writefreely
  README.md
  apps/write-freely/config.json
  apps/write-freely/docker-compose.yml
  apps/write-freely/metadata/description.md
  apps/write-freely/metadata/logo.jpg
Labels: size/L

#5458 Fix errors in config.json of some apps
  apps/calcom/config.json
  apps/esphome/config.json
  apps/grist/config.json
  apps/pinchflat/config.json
  apps/qdirstat/config.json
  apps/transmission-vpn/config.json
  apps/wekan/config.json
  apps/zigbee2mqtt/config.json
Labels: size/S

#5230 jellyfin-vue: Update version to unstable.2024-10-14.a47a7d5
  apps/jellyfin-vue/config.json
  apps/jellyfin-vue/docker-compose.yml
Labels: size/XS

#5462 dozzle dynamic compose
  apps/dozzle/config.json
  apps/dozzle/docker-compose.json
Labels: size/M

#5463 Rss dynamic compose
  apps/rss/config.json
  apps/rss/docker-compose.json
Labels: size/S

#5464 Heimdall dynamic config
  apps/heimdall/config.json
  apps/heimdall/docker-compose.json
Labels: size/S

#5394 Add dynamic compose for librespeed
  apps/librespeed/config.json
  apps/librespeed/docker-compose.json
Labels: size/S

#5395 Add dynamic compose for grist
  apps/grist/config.json
  apps/grist/docker-compose.json
Labels: size/S

#5465 chore: update readme
  templates/README.md
Labels: size/XS

#5400 added workspace extension recommandation biomejs.biome
  .gitignore
  .vscode/extensions.json
Labels: size/XS

#5470 N8n update
  apps/n8n-1/config.json
  apps/n8n-1/docker-compose.yml
Labels: size/XS

#5393 Dynamic compose/grampsweb + Update to last version
  apps/grampsweb/config.json
  apps/grampsweb/docker-compose.json
Labels: size/M

#5396 Add dynamic compose for docmost
  apps/docmost/config.json
  apps/docmost/docker-compose.json
Labels: size/M

#5397 Add dynamic compose for notemark
  apps/notemark/config.json
  apps/notemark/docker-compose.json
Labels: size/M

#5572 refactor(romm): update to latest version
  apps/romm/config.json
  apps/romm/data/config.yml
  apps/romm/docker-compose.yml
  apps/romm/metadata/description.md
  apps/romm/metadata/logo.jpg
Labels: size/L

#5576 Update invidious
  apps/invidious/config.json
  apps/invidious/docker-compose.arm64.yml
  apps/invidious/docker-compose.yml
Labels: size/S

#5613 fix(portainer): rollback
  apps/portainer/config.json
  apps/portainer/docker-compose.yml
Labels: size/S

#5609 fix GUNICORN_NUM_WORKERS from number to tring in grampsweb dynamic compose
  apps/grampsweb/config.json
  apps/grampsweb/docker-compose.json
Labels: size/XS

#5677 chore: change stirling pdf image
  apps/stirling-pdf/config.json
  apps/stirling-pdf/docker-compose.yml
Labels: size/XS

#5714 refactor(beszel-agent): remove fs option
  apps/beszel-agent/config.json
  apps/beszel-agent/docker-compose.json
  apps/beszel-agent/docker-compose.yml
Labels: size/S

#5644 chore(deps): update simplexchat/smp-server docker tag to v6.1.3
  apps/simplex-smp/config.json
  apps/simplex-smp/docker-compose.yml
Labels: size/XS

#5608 Add dynamic compose for cloudflared
  apps/cloudflared/config.json
  apps/cloudflared/docker-compose.json
Labels: size/S

#5581 Add dynamic compose for barrage
  apps/barrage/config.json
  apps/barrage/docker-compose.json
Labels: size/S

#5757 refactor(homarr): remove password
  apps/homarr/config.json
  apps/homarr/docker-compose.yml
Labels: size/S
