Repository runtipi/runtipi-appstore, pull requests merged in 2024-08, with the labels that each got.

#4316 refactor(haven): use latest image
  apps/haven/config.json
  apps/haven/docker-compose.yml
Labels: size/S

#4409 fix(heimdall): https port fixed
  apps/heimdall/docker-compose.yml
Labels: size/XS

#4410 fix(heimdall): store version
  apps/heimdall/config.json
Labels: size/XS

#4428 syncronize config.json and docker-compose.yml versions
  apps/lobe-chat/config.json
Labels: size/XS

#4452 [fix]speedtest tracker
  apps/speedtest-tracker/config.json
  apps/speedtest-tracker/docker-compose.yml
  apps/speedtest-tracker/metadata/description.md
Labels: size/M

#4458 app(esphome): add
  apps/esphome/config.json
  apps/esphome/docker-compose.yml
  apps/esphome/metadata/description.md
  apps/esphome/metadata/logo.jpg
Labels: size/M

#4459 Fix/esp various
  apps/esphome/config.json
  apps/esphome/docker-compose.yml
Labels: size/XS

#4461 fix(esphome): wrong traefik port
  apps/esphome/config.json
  apps/esphome/docker-compose.yml
Labels: size/XS

#4463 Make domain configurable
  apps/invidious/config.json
  apps/invidious/docker-compose.arm64.yml
  apps/invidious/docker-compose.yml
Labels: size/S

#4466 fix(flowise): version mismatch
  apps/flowise/config.json
Labels: size/XS

#4203 chore: update vikunja app to 0.24.1
  apps/vikunja/config.json
  apps/vikunja/data/proxy/nginx.conf
  apps/vikunja/docker-compose.yml
Labels: size/M

#4482 fix(app): Invoice Ninja reverse proxy configuration
  apps/invoice-ninja/config.json
  apps/invoice-ninja/data/nginx/invoice-ninja.conf
  apps/invoice-ninja/docker-compose.yml
Labels: size/M

#4358 update(doozle): improvements
  apps/dozzle/config.json
  apps/dozzle/data/users.yml.template
  apps/dozzle/docker-compose.yml
  apps/dozzle/metadata/description.md
Labels: size/L

#4494 refactor(plausible): qol improvements
  apps/plausible/config.json
  apps/plausible/docker-compose.yml
  apps/plausible/metadata/description.md
Labels: size/L

#4496 chore: deprecate cloudflare-ddns as it is archived
  apps/cloudflare-ddns/config.json
Labels: size/XS

#4503 set fixed version to crowdsecurity/crowdsec:v1.6.2
  apps/crowdsec/config.json
  apps/crowdsec/docker-compose.yml
Labels: size/S

#4504 add(app): lubelogger
  apps/lubelogger/config.json
  apps/lubelogger/data/config/.gitkeep
  apps/lubelogger/data/data/.gitkeep
  apps/lubelogger/data/documents/.gitkeep
  apps/lubelogger/data/images/.gitkeep
  apps/lubelogger/data/keys/.gitkeep
  apps/lubelogger/data/log/.gitkeep
  apps/lubelogger/data/temp/.gitkeep
  apps/lubelogger/docker-compose.yml
  apps/lubelogger/metadata/description.md
  apps/lubelogger/metadata/logo.jpg
Labels: size/L

#4532 chore: update app logos
  apps/calcom/config.json
  apps/calcom/metadata/logo.jpg
  apps/cross-seed/config.json
  apps/cross-seed/metadata/logo.jpg
  apps/crowdsec/config.json
  apps/crowdsec/metadata/logo.jpg
  apps/cyberchef/config.json
  apps/cyberchef/metadata/logo.jpg
  apps/dozzle/config.json
  apps/dozzle/metadata/logo.jpg
  apps/eclipse-mosquitto/config.json
  apps/eclipse-mosquitto/metadata/logo.jpg
  apps/flatnotes/config.json
  apps/flatnotes/metadata/logo.jpg
  apps/grampsweb/config.json
  apps/grampsweb/metadata/logo.jpg
  apps/grist/config.json
  apps/grist/metadata/logo.jpg
  apps/grocy/config.json
  apps/grocy/metadata/logo.jpg
  apps/kimai/config.json
  apps/kimai/metadata/logo.jpg
  apps/lubelogger/config.json
  apps/lubelogger/metadata/logo.jpg
  apps/maintainerr/config.json
  apps/maintainerr/metadata/logo.jpg
  apps/matrix-conduit/config.json
  apps/matrix-conduit/metadata/logo.jpg
  apps/movary/config.json
  apps/movary/metadata/logo.jpg
  apps/nodered/config.json
  apps/nodered/metadata/logo.jpg
  apps/pinchflat/config.json
  apps/pinchflat/metadata/logo.jpg
  apps/postfix-relay/config.json
  apps/postfix-relay/metadata/logo.jpg
  apps/seedsync/config.json
  apps/seedsync/metadata/logo.jpg
  apps/serge/config.json
  apps/serge/metadata/logo.jpg
  apps/shlink/config.json
  apps/shlink/metadata/logo.jpg
  apps/slskd/config.json
  apps/slskd/metadata/logo.jpg
  apps/unmanic/config.json
  apps/unmanic/metadata/logo.jpg
Labels: size/L

#4540 app(lubelogger): improve and fix
  apps/lubelogger/config.json
  apps/lubelogger/data/init/init-db.sh
  apps/lubelogger/docker-compose.json
  apps/lubelogger/docker-compose.yml
Labels: size/L

#4541 fix(lubelogger): db init
  apps/lubelogger/config.json
  apps/lubelogger/docker-compose.json
  apps/lubelogger/docker-compose.yml
Labels: size/XS

#4549 fix(doozle): set default values for envs
  apps/dozzle/config.json
  apps/dozzle/docker-compose.yml
Labels: size/XS

#4552 fix(movary): desc, uid, gid
  apps/movary/config.json
  apps/movary/docker-compose.yml
  apps/movary/metadata/description.md
Labels: size/M

#4553 refactor(flaresolverr): added dynamic config
  apps/flaresolverr/config.json
  apps/flaresolverr/docker-compose.json
Labels: size/S

#4525 Change Calibre to use Media folder instead of App Specific folder
  apps/calibre-web/config.json
  apps/calibre-web/docker-compose.yml
Labels: size/XS

#4555 refactor(vikunja): fix messed up compose and versions
  apps/vikunja/config.json
  apps/vikunja/docker-compose.yml
Labels: size/M

#4554 feat: add beszel app
  apps/__tests__/apps.test.ts
  apps/beszel-agent/config.json
  apps/beszel-agent/docker-compose.yml
  apps/beszel-agent/metadata/description.md
  apps/beszel-agent/metadata/logo.jpg
  apps/beszel/config.json
  apps/beszel/docker-compose.yml
  apps/beszel/metadata/description.md
  apps/beszel/metadata/logo.jpg
Labels: size/L

#4497 add(app): ddns updater
  apps/cloudflare-ddns/metadata/description.md
  apps/ddns-updater/config.json
  apps/ddns-updater/data/config/config.json.template
  apps/ddns-updater/docker-compose.yml
  apps/ddns-updater/metadata/description.md
  apps/ddns-updater/metadata/logo.jpg
Labels: size/L

#4556 fix(beszel): fix traefik labels
  apps/beszel/config.json
  apps/beszel/docker-compose.yml
Labels: size/M

#4557 feat(store): add plausible-ce and deprecate plausible legacy
  apps/plausible-ce/config.json
  apps/plausible-ce/data/clickhouse/clickhouse-config.xml
  apps/plausible-ce/data/clickhouse/clickhouse-user-config.xml
  apps/plausible-ce/docker-compose.json
  apps/plausible-ce/docker-compose.yml
  apps/plausible-ce/metadata/description.md
  apps/plausible-ce/metadata/logo.jpg
  apps/plausible/config.json
Labels: size/XL

#4558 fix(plausible): tokens length
  apps/plausible-ce/config.json
Labels: size/XS

#4559 fix(plausible): env vars typo
  apps/plausible-ce/config.json
  apps/plausible-ce/docker-compose.json
  apps/plausible-ce/docker-compose.yml
Labels: size/M

#4587 fix(ddns-updater): fix config file
  .eslintrc.js
  apps/ddns-updater/config.json
  apps/ddns-updater/data/config/config.json
  apps/ddns-updater/data/config/config.json.template
Labels: size/XS

#4626 Feat/nextcloud mini
  apps/nextcloud-mini/config.json
  apps/nextcloud-mini/docker-compose.json
  apps/nextcloud-mini/docker-compose.yml
  apps/nextcloud-mini/metadata/description.md
  apps/nextcloud-mini/metadata/logo.jpg
Labels: size/L

#4627 refactor: add trusted domains config to nextcloud mini
  apps/nextcloud-mini/config.json
  apps/nextcloud-mini/docker-compose.json
  apps/nextcloud-mini/docker-compose.yml
Labels: size/S
