Repository runtipi/runtipi-appstore, pull requests merged in 2024-05, with the labels that each got.

#3370 Fix invidious healthcheck
  apps/invidious/config.json
  apps/invidious/docker-compose.arm64.yml
  apps/invidious/docker-compose.yml
Labels: size/S

#3386 Invidious config for captions
  apps/invidious/config.json
  apps/invidious/docker-compose.arm64.yml
  apps/invidious/docker-compose.yml
Labels: size/XS

#3384 Fix komga traefik port
  apps/komga/config.json
  apps/komga/docker-compose.yml
Labels: size/XS

#3369 Add label `update-image` to renovate bot PRs
  renovate.json
Labels: size/XS

#3366 Add new config to the bitcoin daemon
  apps/bitcoind/config.json
  apps/bitcoind/docker-compose.yml
Labels: size/M

#3413 Fix: update version in config.json (app/bitcoind)
  apps/bitcoind/config.json
Labels: size/XS

#3412 Update PhotoPrism to v240420
  apps/photoprism/config.json
  apps/photoprism/docker-compose.yml
Labels: size/XS

#3287 App/pinchflat
  apps/pinchflat/config.json
  apps/pinchflat/docker-compose.yml
  apps/pinchflat/metadata/description.md
  apps/pinchflat/metadata/logo.jpg
Labels: size/M

#3383 app/ollama-cpu
  apps/ollama-cpu/config.json
  apps/ollama-cpu/docker-compose.yml
  apps/ollama-cpu/metadata/description.md
  apps/ollama-cpu/metadata/logo.jpg
Labels: size/L

#3381 app/ollama-amd
  apps/ollama-amd/config.json
  apps/ollama-amd/docker-compose.yml
  apps/ollama-amd/metadata/description.md
  apps/ollama-amd/metadata/logo.jpg
Labels: size/L

#3382 app/ollama-nvidia
  apps/ollama-nvidia/config.json
  apps/ollama-nvidia/docker-compose.yml
  apps/ollama-nvidia/metadata/description.md
  apps/ollama-nvidia/metadata/logo.jpg
Labels: size/L

#3430 refactor(readme-generator): display apps in table format
  .github/scripts/readme-generator.ts
  .prettierignore
  .prettierrc
  README.md
  templates/README.md
Labels: size/L

#3437 refactor(readme-generator): use local files instead of fetching remotely
  .github/scripts/readme-generator.ts
  README.md
Labels: size/L

#3460 refactor(getashell): update to 1.0.0
  apps/getashell/config.json
  apps/getashell/docker-compose.yml
  apps/getashell/metadata/description.md
Labels: size/M

#3483 Make readme generator not load app icons
  .github/scripts/readme-generator.ts
  README.md
  templates/README.md
Labels: size/L

#3484 refactor(code-server): small changes in config
  apps/code-server/config.json
  apps/code-server/docker-compose.yml
Labels: size/S

#3492 refactor(openwebui): add dynaminc config option
  apps/__tests__/apps.test.ts
  apps/open-webui/config.json
  apps/schema.json
Labels: size/S

#3493 fix(invoice-ninja): wrong version and missing arm64 architecture
  apps/invoice-ninja/config.json
Labels: size/XS

#3501 Feat/glanceapp
  apps/glance/config.json
  apps/glance/data/glance.yml
  apps/glance/docker-compose.json
  apps/glance/docker-compose.yml
  apps/glance/metadata/description.md
  apps/glance/metadata/logo.jpg
Labels: size/L

#3503 Feat/docker compose json
  .eslintrc.js
  .github/workflows/renovate-app-version.sh
  .prettierrc
  .prettierrc.js
  apps/2fauth/config.json
  apps/2fauth/docker-compose.json
  apps/__tests__/app-config.ts
Labels: size/L

#3497 fix(invoice-ninja): broken compose project
  apps/invoice-ninja/data/nginx/invoice-ninja.conf
  apps/invoice-ninja/docker-compose.yml
Labels: size/M

#3589 Fix/lodestone
  apps/lodestone-core/config.json
  apps/lodestone-core/docker-compose.yml
  apps/lodestone-core/metadata/description.md
Labels: size/M

#3557 fix(n8n): fix initialization error
  apps/n8n-1/config.json
  apps/n8n-1/docker-compose.yml
Labels: size/S

#3590 bitcoind: Use single dash for args and add more value options
  apps/bitcoind/config.json
  apps/bitcoind/docker-compose.yml
Labels: size/M

#3560 fix(invoice-ninja): db not healthy after restart
  apps/invoice-ninja/config.json
  apps/invoice-ninja/docker-compose.yml
Labels: size/S
