Repository runtipi/runtipi-appstore, pull requests merged in 2024-06, with the labels that each got.

#3621 update wg-easy source link
  apps/wg-easy/config.json
Labels: size/XS

#3494 [APP] Suwayomi
  apps/suwayomi/config.json
  apps/suwayomi/docker-compose.yml
  apps/suwayomi/metadata/description.md
  apps/suwayomi/metadata/logo.jpg
Labels: size/M

#3678 Fix windows | sysctl: permission denied on key "net.ipv4.ip_forward"
  apps/windows/docker-compose.yml
Labels: size/XS

#3679 Update Windows config.json
  apps/windows/config.json
Labels: size/XS

#3639 [Homebridge] Avoid the use of the latest version
  apps/homebridge/config.json
  apps/homebridge/docker-compose.yml
Labels: size/XS

#3715 Wraithers mqttx
  apps/mqttx/config.json
  apps/mqttx/docker-compose.yml
  apps/mqttx/metadata/description.md
  apps/mqttx/metadata/logo.jpg
Labels: size/L

#3336 App/electrs
  apps/electrs/config.json
  apps/electrs/docker-compose.yml
  apps/electrs/metadata/description.md
  apps/electrs/metadata/logo.jpg
Labels: size/L

#3732 [App] [Bitcoind]: Listen for rpc calls by default
  apps/bitcoind/config.json
  apps/bitcoind/docker-compose.yml
Labels: size/XS

#3765 fix: update breaking change in immich
  apps/immich/config.json
  apps/immich/docker-compose.yml
Labels: size/M

#3714 Update Invidious for use with external clients
  apps/invidious/config.json
  apps/invidious/docker-compose.arm64.yml
  apps/invidious/docker-compose.yml
Labels: size/S

#3792 fix: update outline oidc provider to point to correct image
  apps/outline/config.json
  apps/outline/docker-compose.yml
Labels: size/XS

#3796 chore(deps): bump prowlarr version
  apps/prowlarr/config.json
  apps/prowlarr/docker-compose.yml
Labels: size/XS

#3802 refactor(tailscale): reworked tailscale app with params
  apps/tailscale/config.json
  apps/tailscale/docker-compose.yml
  apps/tailscale/metadata/description.md
Labels: size/M

#3804 add(mdns-repeater): new app
  apps/homeassistant-1/metadata/description.md
  apps/mdns-repeater/config.json
  apps/mdns-repeater/docker-compose.yml
  apps/mdns-repeater/metadata/description.md
  apps/mdns-repeater/metadata/logo.jpg
Labels: size/M

#3805 fix(mdns): remove networks
  apps/__tests__/apps.test.ts
  apps/mdns-repeater/config.json
  apps/mdns-repeater/docker-compose.yml
Labels: size/XS

#3806 feat(matter): add matter server app
  apps/__tests__/apps.test.ts
  apps/homeassistant-1/metadata/description.md
  apps/matter-server/config.json
  apps/matter-server/docker-compose.yml
  apps/matter-server/metadata/description.md
  apps/matter-server/metadata/logo.jpg
Labels: size/M

#3768 [Bitcoind] Add rpc bind and allow for docker setup
  apps/bitcoind/config.json
  apps/bitcoind/docker-compose.yml
Labels: size/XS

#3843 App/inspircd
  apps/inspircd/config.json
  apps/inspircd/data/.gitkeep
  apps/inspircd/docker-compose.yml
  apps/inspircd/metadata/description.md
  apps/inspircd/metadata/logo.jpg
Labels: size/M

#3860 app(store): add kometa
  apps/kometa/config.json
  apps/kometa/docker-compose.yml
  apps/kometa/metadata/description.md
  apps/kometa/metadata/logo.jpg
Labels: size/L

#3861 fix(kometa): readme
  apps/kometa/metadata/description.md
Labels: size/S

#3868 fix(affine): fix small typo
  apps/affine/docker-compose.yml
Labels: size/XS

#3463 Eclipse Mosquitto updates
  apps/eclipse-mosquitto/config.json
  apps/eclipse-mosquitto/docker-compose.yml
  apps/eclipse-mosquitto/metadata/cedalo_mgm_center.png
  apps/eclipse-mosquitto/metadata/description.md
Labels: size/S

#3717 [App] CyberChef
  apps/cyberchef/config.json
  apps/cyberchef/docker-compose.yml
  apps/cyberchef/metadata/description.md
  apps/cyberchef/metadata/logo.jpg
Labels: size/M

#3881 fix(prowlarr): versionning
  apps/prowlarr/config.json
  apps/prowlarr/docker-compose.yml
Labels: size/XS

#3882 fix(outline): registry url
  apps/outline/config.json
  apps/outline/docker-compose.yml
Labels: size/XS

#3885 update to flowise docker-compose.yml
  apps/flowise/config.json
  apps/flowise/docker-compose.yml
Labels: size/XS

#3886 store(homebox): switch to fork
  apps/homebox/config.json
  apps/homebox/docker-compose.yml
  apps/homebox/metadata/description.md
Labels: size/M

#3887 fix(homebox): docker image version
  apps/homebox/config.json
  apps/homebox/docker-compose.yml
Labels: size/XS

#3907 refactor(ghost-dev): fix wrong data folder
  apps/ghost-dev/config.json
  apps/ghost-dev/docker-compose.yml
  apps/ghost/config.json
Labels: size/S

#3913 refactor(ghost-dev): remove dash from readme
  apps/ghost-dev/config.json
  apps/ghost-dev/metadata/description.md
Labels: size/XS

#3947 feat: guacamole app
  apps/guacamole/config.json
  apps/guacamole/data/init/init-guacamole.sh
  apps/guacamole/data/init/sql/001-create-schema.sql
  apps/guacamole/data/init/sql/002-create-admin-user.sql
  apps/guacamole/docker-compose.yml
  apps/guacamole/metadata/description.md
  apps/guacamole/metadata/logo.jpg
Labels: size/XL

#3950 fix(ghost-dev): fix typo
  apps/ghost-dev/metadata/description.md
Labels: size/XS

#3949 feat: pingvin-share app
  apps/pingvin-share/config.json
  apps/pingvin-share/docker-compose.yml
  apps/pingvin-share/metadata/description.md
  apps/pingvin-share/metadata/logo.jpg
Labels: size/M

#3953 refactor(netbootxyz): use official image
  apps/netbootxyz/config.json
  apps/netbootxyz/docker-compose.yml
Labels: size/S

#3956 refactor(netbootxyz): remove useless port
  apps/netbootxyz/config.json
  apps/netbootxyz/docker-compose.yml
Labels: size/XS

#3960 chore: fix image in matter server
  apps/matter-server/config.json
  apps/matter-server/metadata/logo.jpg
Labels: size/XS

#3961 fix(matter-server): version bumped
  apps/matter-server/config.json
  apps/matter-server/docker-compose.yml
Labels: size/XS

#3906 [App] SiYuan
  apps/siyuan/config.json
  apps/siyuan/docker-compose.yml
  apps/siyuan/metadata/description.md
  apps/siyuan/metadata/logo.jpg
Labels: size/L

#3965 refactor(guacamole): remove arm64 from supported architectures
  apps/guacamole/config.json
Labels: size/XS
