Repository runtipi/runtipi-appstore, pull requests merged in 2025-05, with the labels that each got.

#7683 Invidious: add arm64 dynamic compose
  apps/invidious/config.json
  apps/invidious/docker-compose.arm64.json
Labels: size/M

#7685 Komga: add media directory
  apps/komga/config.json
  apps/komga/docker-compose.json
  apps/komga/docker-compose.yml
Labels: size/XS

#7686 Scrypted: remove default mapped devices
  apps/scrypted/docker-compose.json
Labels: size/XS

#7692 fix(pihole): rename environment variable that changed in v6
  apps/pihole/config.json
  apps/pihole/docker-compose.json
  apps/pihole/docker-compose.yml
Labels: size/XS

#7695 fix(crafty): invalid port range on dynamic compose
  apps/crafty/config.json
  apps/crafty/docker-compose.json
Labels: size/XS

#7696 fix: use correct lb scheme in crafty
  apps/crafty/config.json
  apps/crafty/docker-compose.json
  apps/crafty/docker-compose.yml
Labels: size/M

#7697 fix: use insecure transport in crafty lb
  apps/crafty/config.json
  apps/crafty/docker-compose.json
  apps/crafty/docker-compose.yml
  apps/crafty/metadata/description.md
Labels: size/S

#7698 fix: fix labels in crafty
  apps/crafty/config.json
  apps/crafty/docker-compose.json
  apps/crafty/docker-compose.yml
Labels: size/XS

#7699 fix: use correct labels in transports in crafty
  apps/crafty/config.json
  apps/crafty/docker-compose.json
  apps/crafty/docker-compose.yml
Labels: size/XS

#7700 fix: specify transport location in crafty
  apps/crafty/config.json
  apps/crafty/docker-compose.json
  apps/crafty/docker-compose.yml
Labels: size/XS

#7704 Forgejo: update to v11
  apps/forgejo/config.json
  apps/forgejo/docker-compose.json
  apps/forgejo/docker-compose.yml
Labels: size/S

#7705 refactor: qol improvements in grafana
  apps/grafana/config.json
  apps/grafana/docker-compose.yml
  apps/grafana/metadata/description.md
  apps/grafana/metadata/logo.jpg
Labels: size/M

#7706 updating open-webui from 0.6.5 to 0.6.9
  apps/open-webui/config.json
  apps/open-webui/docker-compose.json
  apps/open-webui/docker-compose.yml
Labels: size/XS

#7711 Update Firefly III
  apps/firefly-iii-data-importer/config.json
  apps/firefly-iii-data-importer/docker-compose.json
  apps/firefly-iii-data-importer/docker-compose.yml
  apps/firefly-iii/config.json
  apps/firefly-iii/docker-compose.json
  apps/firefly-iii/docker-compose.yml
Labels: size/S

#7712 Update paperless-ngx to 2.16.2
  apps/paperless-ngx/config.json
  apps/paperless-ngx/docker-compose.json
  apps/paperless-ngx/docker-compose.yml
Labels: size/XS

#7857 chore(matrix-conduit): update 0.9.0 → 0.10.3 (minor)
  apps/matrix-conduit/config.json
  apps/matrix-conduit/docker-compose.json
  apps/matrix-conduit/docker-compose.yml
Labels: automerge, size/S, minor

#7860 chore(metabase): update 0.54.4 → 0.54.10 (patch)
  apps/metabase/config.json
  apps/metabase/docker-compose.json
  apps/metabase/docker-compose.yml
Labels: automerge, size/S, patch

#7861 chore(octobot): update 2.0.9 → 2.0.10 (patch)
  apps/octobot/config.json
  apps/octobot/docker-compose.json
  apps/octobot/docker-compose.yml
Labels: automerge, size/S, patch

#7863 chore(changedetection): update 0.49.15 → 0.49.18 (patch)
  apps/changedetection/config.json
  apps/changedetection/docker-compose.json
  apps/changedetection/docker-compose.yml
Labels: automerge, size/S, patch

#7864 chore(bewcloud): update 1.5.6 → 1.7.1 (minor)
  apps/bewcloud/config.json
  apps/bewcloud/docker-compose.json
  apps/bewcloud/docker-compose.yml
Labels: automerge, size/S, minor

#7862 chore(pingvin-share): update 1.11.1 → 1.13.0 (minor)
  apps/pingvin-share/config.json
  apps/pingvin-share/docker-compose.json
  apps/pingvin-share/docker-compose.yml
Labels: automerge, size/S, minor

#7868 chore(eclipse-mosquitto): update 2.0.21 → 2.0.21 (patch)
  apps/eclipse-mosquitto/config.json
  apps/eclipse-mosquitto/docker-compose.json
  apps/eclipse-mosquitto/docker-compose.yml
Labels: automerge, patch

#7869 chore(halo): update 2.20.19 → 2.20.21 (patch)
  apps/halo/config.json
  apps/halo/docker-compose.json
  apps/halo/docker-compose.yml
Labels: automerge, patch

#7871 chore(obsidian-livesync): update 3.1.2 → 3.5.0 (minor)
  apps/obsidian-livesync/config.json
  apps/obsidian-livesync/docker-compose.json
  apps/obsidian-livesync/docker-compose.yml
Labels: automerge, minor

#7872 chore(calcom): update 5.0.19 → 5.3.4 (minor)
  apps/calcom/config.json
  apps/calcom/docker-compose.json
  apps/calcom/docker-compose.yml
Labels: automerge, minor

#7879 chore(ghost): update 5.118.1 → 5.120.4 (minor)
  apps/ghost/config.json
Labels: automerge, minor

#7880 chore(tailscale): update 1.82.0 → 1.84.0 (minor)
  apps/tailscale/config.json
Labels: automerge, minor

#7881 chore(nocodb): update 0.262.5 → 0.263.4 (minor)
  apps/nocodb/config.json
Labels: automerge, minor

#7882 chore(rss): update 1.6.0 → 1.6.1 (patch)
  apps/rss/config.json
Labels: automerge, patch

#7883 chore(cloudflared): update 2025.4.0 → 2025.4.2 (patch)
  apps/cloudflared/config.json
Labels: automerge, patch

#7885 chore(siyuan): update 3.1.28 → 3.1.31 (patch)
  apps/siyuan/config.json
Labels: automerge, patch

#7886 chore(immich): update 1.132.3 → 1.134.0 (minor)
  apps/immich/config.json
Labels: automerge, minor

#7887 chore(homeassistant-1): update 2025.4.4 → 2025.5.3 (minor)
  apps/homeassistant-1/config.json
Labels: automerge, minor

#7888 chore(mixpost): update 2.1.3 → 2.2.0 (minor)
  apps/mixpost/config.json
Labels: automerge, minor

#7890 chore(lobe-chat): update 1.83.8 → 1.88.18 (minor)
  apps/lobe-chat/config.json
Labels: automerge, minor

#7891 chore(paperless-ngx): update 2.16.2 → 2.16.2 (minor)
  apps/paperless-ngx/config.json
  apps/paperless-ngx/docker-compose.json
  apps/paperless-ngx/docker-compose.yml
Labels: automerge, minor

#7893 chore(grist): update 1.5.2 → 1.6.0 (minor)
  apps/grist/config.json
  apps/grist/docker-compose.json
  apps/grist/docker-compose.yml
Labels: automerge, minor

#7894 chore(maintainerr): update 2.16.0 → 2.17.0 (minor)
  apps/maintainerr/config.json
  apps/maintainerr/docker-compose.json
  apps/maintainerr/docker-compose.yml
Labels: automerge, minor

#7897 chore(ollama-nvidia): update 0.8.0 → 0.9.0 (minor)
  apps/ollama-nvidia/config.json
  apps/ollama-nvidia/docker-compose.json
  apps/ollama-nvidia/docker-compose.yml
Labels: automerge, minor

#7898 chore(ollama-amd): update 0.8.0 → 0.9.0 (minor)
  apps/ollama-amd/config.json
  apps/ollama-amd/docker-compose.json
  apps/ollama-amd/docker-compose.yml
Labels: automerge, minor

#7899 chore(ollama-cpu): update 0.8.0 → 0.9.0 (minor)
  apps/ollama-cpu/config.json
  apps/ollama-cpu/docker-compose.json
  apps/ollama-cpu/docker-compose.yml
Labels: automerge, minor

#7903 chore(notemark): update 0.15.4 → 0.16.0 (minor)
  apps/notemark/config.json
  apps/notemark/docker-compose.json
  apps/notemark/docker-compose.yml
Labels: automerge, minor

#7904 chore(dozzle): update 8.12.18 → 8.12.19 (patch)
  apps/dozzle/config.json
  apps/dozzle/docker-compose.json
  apps/dozzle/docker-compose.yml
Labels: automerge, patch

#7901 chore(lobe-chat): update 1.88.18 → 1.88.20 (patch)
  apps/lobe-chat/config.json
  apps/lobe-chat/docker-compose.json
  apps/lobe-chat/docker-compose.yml
Labels: automerge, patch

#7913 chore(deps): update getumbrel/electrs docker tag to v0.10.9
  apps/electrs/config.json
  apps/electrs/docker-compose.json
  apps/electrs/docker-compose.yml
Labels: automerge, renovate
