Repository runtipi/runtipi-appstore, pull requests merged in 2025-02, with the labels that each got.

#6599 Add dynamic compose for tailscale
  apps/tailscale/config.json
  apps/tailscale/docker-compose.json
Labels: size/M

#6699 Bewcloud
  apps/bewcloud/config.json
  apps/bewcloud/data/bewcloud/.gitkeep
  apps/bewcloud/docker-compose.json
  apps/bewcloud/docker-compose.yml
  apps/bewcloud/metadata/description.md
  apps/bewcloud/metadata/logo.jpg
Labels: size/L

#6798 refactor: update minio labels
  apps/minio/config.json
  apps/minio/docker-compose.yml
  apps/minio/metadata/description.md
Labels: size/M

#6838 Fix Crowdsec swapped services images
  apps/crowdsec/config.json
  apps/crowdsec/docker-compose.json
Labels: size/XS

#6841 Fix missing dynamic_config option in config (mongo-express, resilio-sync, sshwifty)
  apps/mongo-express/config.json
  apps/resilio-sync/config.json
  apps/sshwifty/config.json
Labels: size/XS

#6803 fix: Use correct env var name for Romm app
  apps/romm/config.json
Labels: size/XS

#6801 fix: Make lubelogger readOnly property camelCase
  apps/lubelogger/config.json
  apps/lubelogger/docker-compose.json
Labels: size/XS

#6874 refactor: force pull latest tags
  apps/affine/config.json
  apps/bitcoind/config.json
  apps/chatpad/config.json
  apps/codex-docs/config.json
  apps/databag/config.json
  apps/deemix/config.json
  apps/deluge/config.json
  apps/dokuwiki/config.json
  apps/duckdns/config.json
  apps/excalidraw/config.json
  apps/filebrowser/config.json
  apps/filestash/config.json
  apps/firefly-iii-data-importer/config.json
  apps/firefly-iii/config.json
  apps/gandi-livedns/config.json
  apps/glances/config.json
  apps/haven/config.json
  apps/hello-world/config.json
  apps/homeassistant/config.json
  apps/homebridge/config.json
  apps/homer/config.json
  apps/invidious/config.json
  apps/it-tools/config.json
  apps/jackett/config.json
  apps/jellyfin-vue/config.json
  apps/kimai/config.json
  apps/libreddit/config.json
  apps/librephotos/config.json
  apps/linkstack/config.json
  apps/mdns-repeater/config.json
  apps/metube/config.json
  apps/minecraft-server/config.json
  apps/minio/config.json
  apps/mixpost-pro/config.json
  apps/monerod/config.json
  apps/nitter/config.json
  apps/odoo/config.json
  apps/olivetin/config.json
  apps/penpot/config.json
  apps/peppermint/config.json
  apps/photoprism/config.json
  apps/pihole/config.json
  apps/podfetch/config.json
  apps/proxitok/config.json
  apps/revolt/config.json
  apps/rsshub/config.json
  apps/scrypted/config.json
  apps/searxng/config.json
  apps/send/config.json
  apps/syncthing/config.json
  apps/teddit/config.json
  apps/unmanic/config.json
  apps/uptime-kuma/config.json
  apps/wekan/config.json
  apps/wg-easy/config.json
  apps/whisparr/config.json
  apps/windows/config.json
  apps/write-freely/config.json
Labels: size/L

#6888 Add dynamic compose for kasm-workspaces
  apps/kasm-workspaces/config.json
  apps/kasm-workspaces/docker-compose.json
Labels: size/M

#6889 Add dynamic compose for moneroblock
  apps/moneroblock/config.json
  apps/moneroblock/docker-compose.json
Labels: size/S

#6891 Add dynamic compose for qbittorrent
  apps/qbittorrent/config.json
  apps/qbittorrent/docker-compose.json
Labels: size/M

#6892 Dynamic compose/rsshub
  apps/rsshub/config.json
  apps/rsshub/docker-compose.json
Labels: size/M

#6893 Add dynamic compose for sftpgo
  apps/sftpgo/config.json
  apps/sftpgo/docker-compose.json
Labels: size/M

#6894 Add dynamic compose for tubearchivist
  apps/tubearchivist/config.json
  apps/tubearchivist/docker-compose.json
Labels: size/M

#6909 Add dynamic compose for zigbee2mqtt
  apps/zigbee2mqtt/config.json
  apps/zigbee2mqtt/docker-compose.json
Labels: size/S

#6914 fix: remove https from portainer
  apps/portainer/config.json
Labels: size/XS
