Repository runtipi/runtipi-appstore, pull requests merged in 2025-03, with the labels that each got.

#6991 Feat/umami analytics
  apps/umami-analytics/config.json
  apps/umami-analytics/docker-compose.json
  apps/umami-analytics/docker-compose.yml
  apps/umami-analytics/metadata/description.md
  apps/umami-analytics/metadata/logo.jpg
  apps/umami/config.json
  apps/umami/metadata/description.md
Labels: size/L

#6994 [archivebox] fix version to 0.7.3
  apps/archivebox/config.json
  apps/archivebox/docker-compose.json
  apps/archivebox/docker-compose.yml
Labels: size/S

#7012 fix: use array instead of dict in smallweb env
  apps/smallweb/config.json
  apps/smallweb/docker-compose.yml
Labels: size/XS

#7024 Add dynamic compose for linkstack
  apps/linkstack/config.json
  apps/linkstack/docker-compose.json
Labels: size/M

#7055 Add dynamic compose for outline
  apps/outline/config.json
  apps/outline/docker-compose.json
Labels: size/L

#7066 Add dynamic compose for traefik-certs-dumper
  apps/traefik-certs-dumper/config.json
  apps/traefik-certs-dumper/docker-compose.json
Labels: size/M

#7065 Add dynamic compose for sabnzbd
  apps/sabnzbd/config.json
  apps/sabnzbd/docker-compose.json
Labels: size/M

#7064 Add dynamic compose for netbootxyz
  apps/netbootxyz/config.json
  apps/netbootxyz/docker-compose.json
Labels: size/M

#7063 Add dynamic compose for mqttx
  apps/mqttx/config.json
  apps/mqttx/docker-compose.json
Labels: size/S

#7061 Add dynamic compose for gandi-livedns
  apps/gandi-livedns/config.json
  apps/gandi-livedns/docker-compose.json
Labels: size/S

#7062 Add dynamic compose for kometa
  apps/kometa/config.json
  apps/kometa/docker-compose.json
Labels: size/M

#7060 Add dynamic compose for inspircd
  apps/inspircd/config.json
  apps/inspircd/docker-compose.json
Labels: size/S

#7057 Add dynamic compose for simplex-smp
  apps/simplex-smp/config.json
  apps/simplex-smp/docker-compose.json
Labels: size/M

#7151 Add dynamic compose for emqx
  apps/emqx/config.json
  apps/emqx/docker-compose.json
Labels: size/M

#7150 Add dynamic compose for stalwart-mail
  apps/stalwart-mail/config.json
  apps/stalwart-mail/docker-compose.json
Labels: size/M

#7149 Add dynamic compose for ollama-amd
  apps/ollama-amd/config.json
  apps/ollama-amd/docker-compose.json
Labels: size/S

#7153 Add dynamic compose for windows
  apps/windows/config.json
  apps/windows/docker-compose.json
Labels: size/M

#7156 Add dynamic compose for nextcloud
  apps/nextcloud/config.json
  apps/nextcloud/docker-compose.json
Labels: size/M

#7157 Add dynamic compose for wg-easy
  apps/wg-easy/config.json
  apps/wg-easy/docker-compose.json
Labels: size/M

#7155 Add dynamic compose for ollama-nvidia
  apps/ollama-nvidia/config.json
  apps/ollama-nvidia/docker-compose.json
Labels: size/M

#7154 Add dynamic compose for transmission-vpn
  apps/transmission-vpn/config.json
  apps/transmission-vpn/docker-compose.json
Labels: size/M

#7158 Add dynamic compose for penpot
  apps/penpot/config.json
  apps/penpot/docker-compose.json
Labels: size/M

#7163 chore: deprecate getashell
  apps/getashell/config.json
  apps/getashell/metadata/description.md
Labels: size/XS

#7164 App/tinyauth
  apps/tinyauth/config.json
  apps/tinyauth/docker-compose.json
  apps/tinyauth/docker-compose.yml
  apps/tinyauth/metadata/description.md
  apps/tinyauth/metadata/logo.jpg
Labels: size/L

#7167 Add dynamic compose for minio
  apps/minio/config.json
  apps/minio/docker-compose.json
Labels: size/M

#7169 Add dynamic compose for smallweb
  apps/smallweb/config.json
  apps/smallweb/docker-compose.json
Labels: size/M

#7173 Add dynamic compose for invoice ninja & rollback to v5.10.62
  apps/invoice-ninja/config.json
  apps/invoice-ninja/docker-compose.json
  apps/invoice-ninja/docker-compose.yml
Labels: size/M

#7168 Add dynamic compose for mastodon
  apps/mastodon/config.json
  apps/mastodon/docker-compose.json
Labels: size/L

#7187 Fix smallweb missing traefik labels
  apps/smallweb/config.json
  apps/smallweb/docker-compose.json
Labels: size/S

#7210 Revert "chore(deps): update invoiceninja/invoiceninja docker tag to v5.11.60" - go back to v5.10
  apps/invoice-ninja/config.json
  apps/invoice-ninja/docker-compose.json
  apps/invoice-ninja/docker-compose.yml
Labels: automerge, size/S

#7249 chore: disable invoiceninja for updates
  renovate.json
Labels: size/XS

#7252 set invoice-ninja to version 5.10.62 and fix nginx
  apps/invoice-ninja/config.json
  apps/invoice-ninja/docker-compose.json
  apps/invoice-ninja/docker-compose.yml
Labels: size/S

#7253 Add dynamic compose for revolt
  apps/revolt/config.json
  apps/revolt/docker-compose.json
Labels: size/L

#7254 Add dynamic compose for matrix-conduit
  apps/matrix-conduit/config.json
  apps/matrix-conduit/docker-compose.json
Labels: size/M

#7260 Update/tinyauth
  apps/tinyauth/config.json
  apps/tinyauth/metadata/description.md
Labels: size/S

#7038 Fix YouTube upload is failing
  apps/n8n-1/config.json
  apps/n8n-1/docker-compose.json
  apps/n8n-1/docker-compose.yml
Labels: size/XS

#7267 fix: don't close external pr if it contains the no close label
  .github/workflows/close-pr.yml
Labels: size/XS

#7285 Fix crowdsec images and block updates (temporarily)
  apps/crowdsec/config.json
  apps/crowdsec/docker-compose.json
  renovate.json
Labels: size/S

#7343 Fix authentik worker version and block update
  apps/authentik/config.json
  apps/authentik/docker-compose.json
  renovate.json
Labels: size/XS

#7344 block immich updates and fix version (temp fix)
  apps/immich/config.json
  apps/immich/docker-compose.json
  renovate.json
Labels: size/XS

#7346 chore: deprecate revolt
  apps/revolt/config.json
Labels: size/XS

#7347 chore: update schemas
  .github/scripts/generate-schemas.ts
  apps/app-info-schema.json
  apps/cross-seed/config.json
  apps/cross-seed/docker-compose.json
  apps/dynamic-compose-schema.json
  apps/homeassistant-1/docker-compose.json
  apps/homebox/docker-compose.json
  apps/mempool/config.json
Labels: size/L

#7349 chore: update smallweb description
  apps/smallweb/config.json
  apps/smallweb/metadata/description.md
Labels: size/S
