Repository runtipi/runtipi-appstore, pull requests merged in 2025-01, with the labels that each got.

#6223 Add dynamic compose for homebox
  apps/homebox/config.json
  apps/homebox/docker-compose.json
Labels: size/S

#6246 feat(affine): add dynamic config
  apps/affine/config.json
  apps/affine/docker-compose.json
Labels: size/M

#6250 Add dynamic compose for bazarr
  apps/bazarr/config.json
  apps/bazarr/docker-compose.json
Labels: size/M

#6251 Add dynamic compose for jackett
  apps/jackett/config.json
  apps/jackett/docker-compose.json
Labels: size/M

#6252 Add dynamic compose for joplin
  apps/joplin/config.json
  apps/joplin/docker-compose.json
Labels: size/M

#6254 Add dynamic compose for libretranslate
  apps/libretranslate/config.json
  apps/libretranslate/docker-compose.json
Labels: size/S

#6255 Add dynamic compose for overseerr
  apps/overseerr/config.json
  apps/overseerr/docker-compose.json
Labels: size/M

#6256 Add dynamic compose for privatebin
  apps/privatebin/config.json
  apps/privatebin/docker-compose.json
Labels: size/S

#6257 Add dynamic compose for radarr
  apps/radarr/config.json
  apps/radarr/docker-compose.json
Labels: size/M

#6258 Add dynamic compose for readarr
  apps/readarr/config.json
  apps/readarr/docker-compose.json
Labels: size/M

#6259 Add dynamic compose for send
  apps/send/config.json
  apps/send/docker-compose.json
Labels: size/M

#6260 Add dynamic compose for sonarr
  apps/sonarr/config.json
  apps/sonarr/docker-compose.json
Labels: size/M

#6261 Add dynamic compose for uptime-kuma
  apps/uptime-kuma/config.json
  apps/uptime-kuma/docker-compose.json
Labels: size/S

#6262 Add dynamic compose for whisparr
  apps/whisparr/config.json
  apps/whisparr/docker-compose.json
Labels: size/M

#6263 Add dynamic compose for dashdot
  apps/dashdot/config.json
  apps/dashdot/docker-compose.json
Labels: size/M

#6264 Add dynamic compose for onedev
  apps/onedev/config.json
  apps/onedev/docker-compose.json
Labels: size/M

#6265 Add dynamic compose for siyuan
  apps/siyuan/config.json
  apps/siyuan/docker-compose.json
Labels: size/S

#6267 Add dynamic compose for cheshire-cat-ai
  apps/cheshire-cat-ai/config.json
  apps/cheshire-cat-ai/docker-compose.json
Labels: size/M

#6270 Add ynamic compose for hedgedoc
  apps/hedgedoc/config.json
  apps/hedgedoc/docker-compose.json
Labels: size/M

#6271 Add dynamic compose for openbooks
  apps/openbooks/config.json
  apps/openbooks/docker-compose.json
Labels: size/S

#6272 Add dynamic compose for plex
  apps/plex/config.json
  apps/plex/docker-compose.json
Labels: size/M

#6268 Dynamic compose/filestash
  apps/filestash/config.json
  apps/filestash/docker-compose.json
Labels: size/M

#6331 Refactor/dynamic bunch 1
  .github/scripts/generate-schemas.ts
  apps/__tests__/app-config.ts
  apps/__tests__/apps.test.ts
  apps/atuin/config.json
  apps/atuin/docker-compose.json
  apps/audiobookshelf/docker-compose.json
  apps/autobrr/config.json
  apps/autobrr/docker-compose.json
  apps/bitcoind/config.json
  apps/bitcoind/docker-compose.json
  apps/bitmagnet/config.json
  apps/bitmagnet/docker-compose.json
  apps/booksonic/config.json
  apps/booksonic/docker-compose.json
  apps/booksonic/docker-compose.yml
  apps/changedetection/docker-compose.json
  apps/cloudflare-ddns/config.json
  apps/cloudflare-ddns/docker-compose.json
  apps/ddns-updater/data/config/config.json
  apps/mealie-1/config.json
  apps/mealie-1/docker-compose.json
  apps/mealie/config.json
  apps/mealie/docker-compose.json
  apps/mempool/config.json
  apps/mempool/docker-compose.json
  apps/minecraft-server/config.json
  apps/minecraft-server/docker-compose.json
  e2e/fixtures/fixtures.ts
  e2e/helpers/helpers.ts
  e2e/install.spec.ts
  playwright.config.ts
  renovate.json
Labels: size/XL

#6330 Add dynamic compose for nocodb
  apps/nocodb/config.json
  apps/nocodb/docker-compose.json
Labels: size/M

#6313 Add dynamic compose for drawio
  apps/drawio/config.json
  apps/drawio/docker-compose.json
Labels: size/S

#6335 chore: migrate authentik to dynamic config
  apps/authentik/config.json
  apps/authentik/docker-compose.json
Labels: size/L

#6340 fix: use correct port in authentik
  apps/authentik/config.json
  apps/authentik/docker-compose.json
Labels: size/XS

#6338 Add dynamic compose for portainer
  apps/portainer/config.json
  apps/portainer/docker-compose.json
Labels: size/S

#6348 Add dynamic compose for owncloud
  apps/owncloud/config.json
  apps/owncloud/docker-compose.json
Labels: size/M

#6346 Add dynamic compose for glances
  apps/glances/config.json
  apps/glances/docker-compose.json
Labels: size/S

#6343 Add dynamic compose for stirling-pdf
  apps/stirling-pdf/config.json
  apps/stirling-pdf/docker-compose.json
Labels: size/M

#6339 Add dynamic compose for photoprism
  apps/photoprism/config.json
  apps/photoprism/docker-compose.json
Labels: size/M

#5889 Add dynamic compose for homeassistant-1
  apps/homeassistant-1/config.json
  apps/homeassistant-1/docker-compose.json
Labels: size/S

#6375 feat: show dynamic config count in readme
  .github/scripts/readme-generator.ts
  README.md
  templates/README.md
Labels: size/XL

#6377 chore: rename dynamic config to dynamic
  README.md
  templates/README.md
Labels: size/XL

#6374 [Mixpost] fix db healthcheck and update description for initial startup
  apps/mixpost-pro/config.json
  apps/mixpost-pro/docker-compose.json
  apps/mixpost-pro/metadata/description.md
  apps/mixpost/config.json
  apps/mixpost/docker-compose.json
  apps/mixpost/metadata/description.md
Labels: size/M

#6378 deprecate libreddit
  apps/libreddit/config.json
Labels: size/XS

#6381 cyberchef - remove arm64 (unsupported)
  apps/cyberchef/config.json
Labels: size/XS

#6363 Add dynamic compose for gotosocial
  apps/gotosocial/config.json
  apps/gotosocial/docker-compose.json
Labels: size/M

#6355 Add dynamic compose for movary
  apps/movary/config.json
  apps/movary/docker-compose.json
Labels: size/M

#6354 Add dynamic compose for rallly
  apps/rallly/config.json
  apps/rallly/docker-compose.json
Labels: size/M

#6347 Add dynamic compose for forgejo
  apps/forgejo/config.json
  apps/forgejo/docker-compose.json
Labels: size/M

#6344 Add dynamic compose for wikijs
  apps/wikijs/config.json
  apps/wikijs/docker-compose.json
Labels: size/M

#6385 Add dynamic compose for unmanic + change docker tag
  apps/unmanic/config.json
  apps/unmanic/docker-compose.json
  apps/unmanic/docker-compose.yml
Labels: size/M

#6405 Revert "Update lscr.io/linuxserver/qbittorrent Docker tag to v20"
  apps/qbittorrent/config.json
  apps/qbittorrent/docker-compose.yml
Labels: automerge, size/XS

#6411 Remove usage of docker.io registry
  apps/bitmagnet/docker-compose.json
  apps/bitmagnet/docker-compose.yml
  apps/paperless-ngx/docker-compose.json
  apps/paperless-ngx/docker-compose.yml
  apps/sftpgo/docker-compose.yml
  apps/shlink/docker-compose.json
  apps/shlink/docker-compose.yml
Labels: size/S

#6406 Add dynamic compose for ghostfolio
  apps/ghostfolio/config.json
  apps/ghostfolio/docker-compose.json
Labels: size/M

#6418 Add dynamic compose flowise (and fix paths)
  apps/flowise/config.json
  apps/flowise/docker-compose.json
  apps/flowise/docker-compose.yml
Labels: size/M

#6424 Refactor/dynamic bunch 2
  apps/__tests__/apps.test.ts
  apps/codex-docs/config.json
  apps/codex-docs/docker-compose.json
  apps/crafty/config.json
  apps/crafty/docker-compose.json
  apps/cross-seed/config.json
  apps/cross-seed/docker-compose.json
  apps/crowdsec/config.json
  apps/crowdsec/docker-compose.json
  apps/ddns-updater/config.json
  apps/ddns-updater/docker-compose.json
  apps/ddns-updater/metadata/description.md
  apps/duckdns/config.json
  apps/duckdns/docker-compose.json
Labels: size/L

#6425 Add dynamic compose for your-spotify
  apps/your-spotify/config.json
  apps/your-spotify/docker-compose.json
Labels: size/M

#6429 feat(mosquitto): add dynamic configuration support and update tipi version
  apps/eclipse-mosquitto/config.json
  apps/eclipse-mosquitto/docker-compose.json
Labels: size/M

#6428 feat(duplicati): add dynamic configuration and docker-compose setup
  apps/duplicati/config.json
  apps/duplicati/docker-compose.json
Labels: size/M

#6442 fix(lubelogger): connection string
  apps/lubelogger/config.json
  apps/lubelogger/docker-compose.json
Labels: size/XS

#6448 rallly: fix db healthcheck
  apps/rallly/docker-compose.json
Labels: size/XS

#6436 Fix Plausible-CE Install and add healthcheck
  apps/plausible-ce/config.json
  apps/plausible-ce/docker-compose.json
Labels: size/S

#6434 Add dynamic compose for planka (and fix the app)
  apps/planka/config.json
  apps/planka/docker-compose.json
Labels: size/M

#6432 Add dynamic compose for transmission
  apps/transmission/config.json
  apps/transmission/docker-compose.json
Labels: size/M

#6433 Add dynamic compose for wordpress
  apps/wordpress/config.json
  apps/wordpress/docker-compose.json
Labels: size/M

#6435 Add dynamic compose for romm
  apps/romm/config.json
  apps/romm/docker-compose.json
Labels: size/M

#6437 Add dynamic compose for plausible
  apps/plausible/config.json
  apps/plausible/docker-compose.json
Labels: size/M

#6440 Add dynamic compose for umami
  apps/umami/config.json
  apps/umami/docker-compose.json
Labels: size/M

#6441 Add dynamic compose for emulatorjs
  apps/emulatorjs/config.json
  apps/emulatorjs/docker-compose.json
Labels: size/M

#6451 Add dynamic compose for postfix-relay
  apps/postfix-relay/config.json
  apps/postfix-relay/docker-compose.json
Labels: size/M

#6457 Add dynamic compose for resilio-sync
  apps/resilio-sync/config.json
  apps/resilio-sync/docker-compose.json
Labels: size/M

#6458 Add dynamic compose for slskd
  apps/slskd/config.json
  apps/slskd/docker-compose.json
Labels: size/M

#6459 Add dynamic compose for speedtest tracker
  apps/speedtest-tracker/config.json
  apps/speedtest-tracker/docker-compose.json
Labels: size/M

#6462 Add dynamic compose for ghost-dev
  apps/ghost-dev/config.json
  apps/ghost-dev/docker-compose.json
Labels: size/S

#6486 Add dynamic compose for syncthing
  apps/syncthing/config.json
  apps/syncthing/docker-compose.json
Labels: size/M

#6485 Add dynamic compose for invidious
  apps/invidious/config.json
  apps/invidious/docker-compose.json
Labels: size/M

#6484 Add dynamic compose for kiwix-serve
  apps/kiwix-serve/config.json
  apps/kiwix-serve/docker-compose.json
Labels: size/S

#6477 Add dynamic compose for immich
  apps/immich/config.json
  apps/immich/docker-compose.json
Labels: size/M

#6512 Add dynamic compose for peppermint
  apps/peppermint/config.json
  apps/peppermint/docker-compose.json
Labels: size/M

#6516 Add dynamic compose for firefly-iii-data-importer
  apps/firefly-iii-data-importer/config.json
  apps/firefly-iii-data-importer/docker-compose.json
Labels: size/S

#6520 Add dynamic compose for seedsync
  apps/seedsync/config.json
  apps/seedsync/docker-compose.json
Labels: size/M

#6524 Add dynamic compose for mylar3
  apps/mylar3/config.json
  apps/mylar3/docker-compose.json
Labels: size/M

#6525 Add dynamic compose for proxitok
  apps/proxitok/config.json
  apps/proxitok/docker-compose.json
Labels: size/M

#6529 nextgba: fix image path
  apps/nextgba/docker-compose.json
Labels: size/XS

#6531 Add dynamic compose for homeassistant (unexposed)
  apps/homeassistant/config.json
  apps/homeassistant/docker-compose.json
Labels: size/S

#6527 Add dynamic compose for scrypted
  apps/scrypted/config.json
  apps/scrypted/docker-compose.json
Labels: size/M

#6532 Add dynamic compose for write-freely
  apps/write-freely/config.json
  apps/write-freely/docker-compose.json
Labels: size/M

#6533 Add dynamic compose for matter-server
  apps/matter-server/config.json
  apps/matter-server/docker-compose.json
Labels: size/S

#6534 Add dynamic compose for octobot
  apps/octobot/config.json
  apps/octobot/docker-compose.json
Labels: size/M

#6535 Add dynamic compose for tooljet
  apps/tooljet/config.json
  apps/tooljet/docker-compose.json
Labels: size/M

#6536 Add dynamic compose for homebridge
  apps/homebridge/config.json
  apps/homebridge/docker-compose.json
Labels: size/M

#6537 Add dynamic compose for pihole
  apps/pihole/config.json
  apps/pihole/docker-compose.json
Labels: size/M

#6538 Add dynamic compose for suwayomi
  apps/suwayomi/config.json
  apps/suwayomi/docker-compose.json
Labels: size/S

#6541 Add dynamic compose for qdirstat
  apps/qdirstat/config.json
  apps/qdirstat/docker-compose.json
Labels: size/M

#6542 Add dynamic compose for zerotier
  apps/zerotier/config.json
  apps/zerotier/docker-compose.json
Labels: size/S

#6543 Add dynamic compose for recyclarr
  apps/recyclarr/config.json
  apps/recyclarr/docker-compose.json
Labels: size/S

#6559 Add dynamic compose for lodestone-core
  apps/lodestone-core/config.json
  apps/lodestone-core/docker-compose.json
Labels: size/S

#6560 Add dynamic compose for nitter
  apps/nitter/config.json
  apps/nitter/docker-compose.json
Labels: size/M

#6565 Add dynamic compose for gladys
  apps/gladys/config.json
  apps/gladys/docker-compose.json
Labels: size/M

#6566 Add dynamic compose for semaphore
  apps/semaphore/config.json
  apps/semaphore/docker-compose.json
Labels: size/M

#6564 Add dynamic compos for n8n-1
  apps/n8n-1/config.json
  apps/n8n-1/docker-compose.json
Labels: size/M
